# Use four public NTP servers from the pool.ntp.org project.
#pool pool.ntp.org iburst

# Server NTP istituzionali italiani
# INRiM - Istituto Nazionale di Ricerca Metrologica (Torino)
# Riferimento primario del tempo in Italia - orologi atomici nazionali
server ntp1.inrim.it iburst
server ntp2.inrim.it iburst

# INFN - Istituto Nazionale di Fisica Nucleare
server ntp.infn.it iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync
